IF DB_ID('OnlineBusiness') IS NOT NULL
BEGIN
	USE master;
	DROP DATABASE [OnlineBusiness]
END

--Tạo Database--
CREATE DATABASE [OnlineBusiness]
GO

USE [OnlineBusiness]

-- Tao bang
 
-- Tao bang [KHACHHANG]
CREATE TABLE [KHACHHANG] (
	MaKH int NOT NULL,
	TenKH nvarchar(50) NOT NULL,
	DiaChi nvarchar(100) NOT NULL,
	SDT varchar(10) NOT NULL,
	Gmail varchar(30) NOT NULL,
	PRIMARY KEY (MaKH)
)
GO

-- Tao bang [LOAISANPHAM]
CREATE TABLE [LOAISANPHAM] (
	MaLoai int NOT NULL,
	TenLoai nvarchar(50) NOT NULL,
	PRIMARY KEY (MaLoai)
)
GO

-- Tao bang [SANPHAM]
CREATE TABLE [SANPHAM] (
	MaSP int NOT NULL,
	TenSP nvarchar(50) NOT NULL,
	MoTa nvarchar(100) NOT NULL,
	MaLoai int NOT NULL,
	SoLuongTon int NOT NULL CHECK (SoLuongTon >= 0),
	Gia int NOT NULL,
	PRIMARY KEY (MaSP)
)
GO

-- Tao bang [NHANVIEN]
CREATE TABLE [NHANVIEN] (
	MaNV int NOT NULL,
	TenNV nvarchar(50) NOT NULL,
	ChucVu nvarchar(50) NOT NULL,
	SDT varchar(10) NOT NULL,
	DiaChi nvarchar(100) NOT NULL,
	PRIMARY KEY (MaNV)
)
GO

-- Tao bang [DOITAC]
CREATE TABLE [DOITAC] (
	MaDT int NOT NULL,
	TenDT nvarchar(50) NOT NULL,
	DiaChi nvarchar(100) NOT NULL,
	SDT varchar(10),
	Gmail VARCHAR(50),
	PRIMARY KEY (MaDT)
)
GO

-- Tao bang [GIOHANG]
CREATE TABLE [GIOHANG] (
	MaGH int NOT NULL,
	MaKH int NOT NULL,
	TongTien int,
	TrangThai nvarchar(20) CHECK (TrangThai = N'tiếp nhận' OR TrangThai = N'ngưng tiếp nhận'),
	PRIMARY KEY (MaGH)
)
GO

-- Tao bang [CTGIOHANG]
CREATE TABLE [CTGIOHANG] (
	MaCTGH int NOT NULL,
	MaGH int NOT NULL,
	MaSP int NOT NULL,
	SoLuong int NOT NULL CHECK (SoLuong >= 0),
	ThanhTien int,
	TrangThai nvarchar(20) NOT NULL CHECK (TrangThai = N'tốt' OR TrangThai = N'lỗi'),
	PRIMARY KEY (MaCTGH)
)
GO

-- Tao bang [PTTHANHTOAN]
CREATE TABLE [PTTHANHTOAN](
	MaPT int NOT NULL,
	TenPT nvarchar(20) NOT NULL,
	PRIMARY KEY (MaPT)
)
GO

-- Tao bang [HOADON]
CREATE TABLE [HOADON] (
	MaHD int NOT NULL,
	MaGH int NOT NULL,
	NgayLap date NOT NULL,
	TrangThai nvarchar(20) NOT NULL CHECK (TrangThai = N'chưa xác nhận' OR TrangThai = N'đã xác nhận' OR TrangThai = N'đang giao' OR TrangThai = N'hoàn tất'),
	SDT varchar(10) NOT NULL,
	Gmail varchar(30) NOT NULL,
	DiaChi nvarchar(100) NOT NULL,
	MaPT int NOT NULL,
	TongTien int,
	MaNV int NOT NULL,
	PRIMARY KEY (MaHD)
)
GO

-- Tao bang [THONGTINTRAHANG]
CREATE TABLE [THONGTINTRAHANG] (
	MaTH int NOT NULL,
	MaCTGH int NOT NULL,
	LyDoTra nvarchar(100) NOT NULL,
	NgayTra date NOT NULL,
	TienHoanTra int,
	TrangThai nvarchar(20) NOT NULL CHECK (TrangThai = N'chờ xử lý' OR TrangThai = N'đang xử lý' OR TrangThai = N'đã xử lý'),
	PRIMARY KEY (MaTH)
)
GO

-- Tao bang [COMMENT]
CREATE TABLE [COMMENT] (
	MaCMT int NOT NULL,
	NgayLap date NOT NULL,
	Sao int NOT NULL CHECK (Sao >= 1 AND Sao <= 5),
	NoiDung nvarchar(200),
	Loai nvarchar(10) CHECK (Loai = NULL OR Loai = N'Tốt' OR Loai = N'Xấu'),
	MaKH int NOT NULL,
	MaSP int NOT NULL,
	TrangThai nvarchar(20) NOT NULL CHECK (TrangThai = N'đã đăng' OR TrangThai = N'không được đăng' OR TrangThai = N'đã tặng quà'),
	PRIMARY KEY (MaCMT)
)
GO

-- Tao bang [TINNHAN]
CREATE TABLE [TINNHAN] (
	MaTN INT NOT NULL PRIMARY KEY,
	MaSP INT NOT NULL,
	Tuan INT NOT NULL,-- Tuan Lap
	Nam INT NOT NULL,
	ChuDe NVARCHAR(50),
	NoiDung NVARCHAR(MAX),
)
GO

-- Tao bang [TINNHAN_KHACHHANG]
CREATE TABLE TINNHAN_KHACHHANG (
	MaTN INT NOT NULL,
	MaKH INT NOT NULL,
	PRIMARY KEY (MaTN, MaKH)
)
GO

-- Tao bang [DOITACBANHANG]
CREATE TABLE [DOITACBANHANG](
	MaDT int NOT NULL,
	TenDT nvarchar(50) NOT NULL,
	NgayBatDauHopTac date NOT NULL,
	PRIMARY KEY (MaDT)
)
GO

-- Tao bang [DONNHAPHANG]
CREATE TABLE [DONNHAPHANG](
	MaDNH int NOT NULL,
	MaDTBH int NOT NULL,
	MaNV int NOT NULL,
	NgayLap date NOT NULL,
	LyDoNhap nvarchar(100) NOT NULL,
	TongTien int,
	PRIMARY KEY (MaDNH)
)
GO

-- Tao bang [CTDONNHAPHANG]
CREATE TABLE [CTDONNHAPHANG](
	MaDNH int NOT NULL,
	MaSP int NOT NULL,
	SoLuong int NOT NULL CHECK (SoLuong >= 0),
	Gia int NOT NULL,
	PRIMARY KEY (MaDNH, MaSP)
)
GO

-- Tao bang [DONTRAHANG]
CREATE TABLE [DONTRAHANG](
	MaDTH int NOT NULL,
	MaNV int NOT NULL,
	NgayLap date NOT NULL,
	MaDTBH int NOT NULL,
	LyDoTra nvarchar(200) NOT NULL,
	PRIMARY KEY (MaDTH)
)
GO

-- Tao bang [CTDONTRAHANG]
CREATE TABLE [CTDONTRAHANG](
	MaDTH int NOT NULL,
	MaSP int NOT NULL,
	SoLuong int NOT NULL CHECK (SoLuong >= 0),
	PRIMARY KEY (MaDTH, MaSP)
)
GO

-- Tao bang [HOPDONG]
CREATE TABLE [HOPDONG](
	MaHD int NOT NULL,
	TenHD nvarchar(50) NOT NULL,
	MaDT int NOT NULL,
	MaNV int NOT NULL,
	NgayLap date NOT NULL,
	ThoiHan date NOT NULL,
	NoiDung nvarchar(max) NOT NULL,
	ViTriDang NVARCHAR(max),
	PRIMARY KEY (MaHD)
)
GO

-- Tao rang buoc khoa ngoai

ALTER TABLE [GIOHANG] 
	ADD CONSTRAINT FK_GH_KH
	FOREIGN KEY (MaKH) 
	REFERENCES [KHACHHANG](MaKH)
GO

ALTER TABLE [COMMENT] 
	ADD CONSTRAINT FK_CMT_KH
	FOREIGN KEY (MaKH) 
	REFERENCES [KHACHHANG](MaKH)
GO

ALTER TABLE [COMMENT] 
	ADD CONSTRAINT FK_CMT_SP
	FOREIGN KEY (MaSP) 
	REFERENCES [SANPHAM](MaSP)
GO

ALTER TABLE [SANPHAM] 
	ADD CONSTRAINT FK_SP_LSP
	FOREIGN KEY (MaLoai) 
	REFERENCES [LOAISANPHAM](MaLoai)
GO

ALTER TABLE [TINNHAN]
	ADD CONSTRAINT FK_TN_SP
	FOREIGN KEY (MaSP)
	REFERENCES SANPHAM(MaSP)
GO

ALTER TABLE [TINNHAN_KHACHHANG]
	ADD CONSTRAINT FK_TNKH_KH
	FOREIGN KEY (MaKH)
	REFERENCES KHACHHANG(MaKH)
GO

ALTER TABLE [TINNHAN_KHACHHANG]
	ADD CONSTRAINT FK_TNKH_TN
	FOREIGN KEY (MaTN)
	REFERENCES TINNHAN(MaTN)
GO

ALTER TABLE [CTGIOHANG] 
	ADD CONSTRAINT FK_CTGH_GH
	FOREIGN KEY (MaGH) 
	REFERENCES [GIOHANG](MaGH)
GO

ALTER TABLE [CTGIOHANG] 
	ADD CONSTRAINT FK_CTGH_SP
	FOREIGN KEY (MaSP) 
	REFERENCES [SANPHAM](MaSP)
GO

ALTER TABLE [DONNHAPHANG] 
	ADD CONSTRAINT FK_DNH_DTBH
	FOREIGN KEY (MaDTBH) 
	REFERENCES [DOITACBANHANG](MaDT)
GO

ALTER TABLE [DONNHAPHANG] 
	ADD CONSTRAINT FK_DNH_NV
	FOREIGN KEY (MaNV) 
	REFERENCES [NHANVIEN](MaNV)
GO

ALTER TABLE [CTDONNHAPHANG] 
	ADD CONSTRAINT FK_CTDNH_DNH
	FOREIGN KEY (MaDNH) 
	REFERENCES [DONNHAPHANG](MaDNH)
GO

ALTER TABLE [CTDONNHAPHANG] 
	ADD CONSTRAINT FK_CTDNH_SP
	FOREIGN KEY (MaSP) 
	REFERENCES [SANPHAM](MaSP)
GO

ALTER TABLE [THONGTINTRAHANG] 
	ADD CONSTRAINT FK_TTTH_CTGH
	FOREIGN KEY (MaCTGH) 
	REFERENCES [CTGIOHANG](MaCTGH)
GO

ALTER TABLE [DONTRAHANG] 
	ADD CONSTRAINT FK_DTH_NV
	FOREIGN KEY (MaNV) 
	REFERENCES [NHANVIEN](MaNV)
GO

ALTER TABLE [DONTRAHANG] 
	ADD CONSTRAINT FK_DTH_DTBH
	FOREIGN KEY (MaDTBH) 
	REFERENCES [DOITACBANHANG](MaDT)
GO

ALTER TABLE [CTDONTRAHANG] 
	ADD CONSTRAINT FK_CTDTH_DTH
	FOREIGN KEY (MaDTH) 
	REFERENCES [DONTRAHANG](MaDTH)
GO

ALTER TABLE [CTDONTRAHANG] 
	ADD CONSTRAINT FK_CTDTH_SP
	FOREIGN KEY (MaSP) 
	REFERENCES [SANPHAM](MaSP)
GO

ALTER TABLE [HOPDONG] 
	ADD CONSTRAINT FK_HD_DT
	FOREIGN KEY (MaDT) 
	REFERENCES [DOITAC](MaDT)
GO

ALTER TABLE [HOPDONG] 
	ADD CONSTRAINT FK_HD_NV
	FOREIGN KEY (MaNV) 
	REFERENCES [NHANVIEN](MaNV)
GO

ALTER TABLE [HOADON] 
	ADD CONSTRAINT FK_HOADON_PTTT
	FOREIGN KEY (MaPT) 
	REFERENCES [PTTHANHTOAN](MaPT)
GO

ALTER TABLE [HOADON] 
	ADD CONSTRAINT FK_HOADON_GH
	FOREIGN KEY (MaGH) 
	REFERENCES [GIOHANG](MaGH)
GO

ALTER TABLE [HOADON] 
	ADD CONSTRAINT FK_HOADON_NV
	FOREIGN KEY (MaNV) 
	REFERENCES [NHANVIEN](MaNV)
GO